title: "Anthony's Blog"
baseurl: "https://example.com/"
copyright: ""
theme: "hugo-devblog-theme"

# summaryLength of 30 fits the demo template
summaryLength: 30

# paginate of 6 is same as demo template
paginate: 6

mainSections:
- blog

# taxonomies:
#   tag: "tags"
#   category: "categories"
#   publication_type: "publication_types"
#   author: "authors"