# Main menu for site, shown on left side
# `pre` defines the icon to use for item. See https://fontawesome.com/icons?d=gallery
# for a list of available fontawesome icons to use

main:
- name: Home
  url: /
  pre: home
  weight: 10
- name: Blog
  url: /blog
  pre: bookmark
  weight: 20
- name: About Me
  url: /about
  pre: user
  weight: 30